const countriesTypes = {
  FETCH_DATA_START: "FETCH_DATA_START",
  FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
  SET_REGION: "SET_REGION",
  SET_NAME: "SET_NAME",
  TOGGLE_LOADING: "TOGGLE_LOADING",
};

export default countriesTypes;
